import pandas as pd


data_completa = {
  "comando": [
    "accent-color",
    "align-content",
    "align-items",
    "align-self",
    "alignment-adjust",
    "alignment-baseline",
    "all",
    "anchor-point",
    "animation",
    "animation-delay",
    "animation-direction",
    "animation-duration",
    "animation-fill-mode",
    "animation-iteration-count",
    "animation-name",
    "animation-play-state",
    "animation-timing-function",
    "appearance",
    "aspect-ratio",
    "backdrop-filter",
    "backface-visibility",
    "background",
    "background-attachment",
    "background-blend-mode",
    "background-clip",
    "background-color",
    "background-image",
    "background-origin",
    "background-position",
    "background-repeat",
    "background-size",
    "baseline-shift",
    "block-size",
    "border",
    "border-block",
    "border-block-color",
    "border-block-end",
    "border-block-end-color",
    "border-block-end-style",
    "border-block-end-width",
    "border-block-start",
    "border-block-start-color",
    "border-block-start-style",
    "border-block-start-width",
    "border-block-style",
    "border-block-width",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-bottom-style",
    "border-bottom-width",
    "border-collapse",
    "border-color",
    "border-end-end-radius",
    "border-end-start-radius",
    "border-image",
    "border-image-outset",
    "border-image-repeat",
    "border-image-slice",
    "border-image-source",
    "border-image-width",
    "border-inline",
    "border-inline-color",
    "border-inline-end",
    "border-inline-end-color",
    "border-inline-end-style",
    "border-inline-end-width",
    "border-inline-start",
    "border-inline-start-color",
    "border-inline-start-style",
    "border-inline-start-width",
    "border-inline-style",
    "border-inline-width",
    "border-left",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-radius",
    "border-right",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-spacing",
    "border-start-end-radius",
    "border-start-start-radius",
    "border-style",
    "border-top",
    "border-top-color",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-top-style",
    "border-top-width",
    "border-width",
    "bottom",
    "box-decoration-break",
    "box-shadow",
    "box-sizing",
    "break-after",
    "break-before",
    "break-inside",
    "caption-side",
    "caret-color",
    "clear",
    "clip",
    "clip-path",
    "color",
    "color-adjust",
    "column-count",
    "column-fill",
    "column-gap",
    "column-rule",
    "column-rule-color",
    "column-rule-style",
    "column-rule-width",
    "column-span",
    "column-width",
    "columns",
    "contain",
    "content",
    "counter-increment",
    "counter-reset",
    "counter-set",
    "cue",
    "cue-after",
    "cue-before",
    "cursor",
    "direction",
    "display",
    "empty-cells",
    "filter",
    "flex",
    "flex-basis",
    "flex-direction",
    "flex-flow",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
    "float",
    "flood-color",
    "flood-opacity",
    "flow-from",
    "flow-into",
    "font",
    "font-family",
    "font-feature-settings",
    "font-kerning",
    "font-language-override",
    "font-optical-sizing",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-synthesis",
    "font-variant",
    "font-variant-caps",
    "font-variant-east-asian",
    "font-variant-ligatures",
    "font-variant-numeric",
    "font-variant-position",
    "font-weight",
    "gap",
    "glyph-orientation-vertical",
    "grid",
    "grid-area",
    "grid-auto-columns",
    "grid-auto-flow",
    "grid-auto-rows",
    "grid-column",
    "grid-column-end",
    "grid-column-gap",
    "grid-column-start",
    "grid-gap",
    "grid-row",
    "grid-row-end",
    "grid-row-gap",
    "grid-row-start",
    "grid-template",
    "grid-template-areas",
    "grid-template-columns",
    "grid-template-rows",
    "hanging-punctuation",
    "height",
    "hyphens",
    "image-orientation",
    "image-rendering",
    "image-resolution",
    "ime-mode",
    "initial-letters",
    "initial-letters-align",
    "inline-size",
    "inline-box-align",
    "justify-content",
    "justify-items",
    "justify-self",
    "left",
    "letter-spacing",
    "lighting-color",
    "line-break",
    "line-clamp",
    "line-height",
    "line-height-step",
    "list-style",
    "list-style-image",
    "list-style-position",
    "list-style-type",
    "margin",
    "margin-block",
    "margin-block-end",
    "margin-block-start",
    "margin-bottom",
    "margin-inline",
    "margin-inline-end",
    "margin-inline-start",
    "margin-left",
    "margin-right",
    "margin-top",
    "marker",
    "marker-end",
    "marker-knockout-left",
    "marker-knockout-right",
    "marker-mid",
    "marker-pattern",
    "marker-segment",
    "marker-side",
    "marker-start",
    "mask",
    "mask-box",
    "mask-box-outset",
    "mask-box-repeat",
    "mask-box-slice",
    "mask-box-source",
    "mask-box-width",
    "mask-clip",
    "mask-composite",
    "mask-image",
    "mask-mode",
    "mask-origin",
    "mask-position",
    "mask-repeat",
    "mask-size",
    "mask-source-type",
    "mask-type",
    "max-block-size",
    "max-height",
    "max-inline-size",
    "max-width",
    "min-block-size",
    "min-height",
    "min-inline-size",
    "min-width",
    "mix-blend-mode",
    "move-to",
    "nav-down",
    "nav-left",
    "nav-right",
    "nav-up",
    "object-fit",
    "object-position",
    "offset",
    "offset-anchor",
    "offset-distance",
    "offset-path",
    "offset-position",
    "offset-rotate",
    "opacity",
    "order",
    "orphans",
    "outline",
    "outline-color",
    "outline-offset",
    "outline-style",
    "outline-width",
    "overflow",
    "overflow-block",
    "overflow-inline",
    "overflow-wrap",
    "overflow-x",
    "overflow-y",
    "padding",
    "padding-block",
    "padding-block-end",
    "padding-block-start",
    "padding-bottom",
    "padding-inline",
    "padding-inline-end",
    "padding-inline-start",
    "padding-left",
    "padding-right",
    "padding-top",
    "page",
    "page-break-after",
    "page-break-before",
    "page-break-inside",
    "pause",
    "pause-after",
    "pause-before",
    "perspective",
    "perspective-origin",
    "pitch",
    "pitch-range",
    "place-content",
    "place-items",
    "place-self",
    "play-during",
    "pointer-events",
    "position",
    "quotes",
    "region-break-after",
    "region-break-before",
    "region-break-inside",
    "region-fragment",
    "resize",
    "rest",
    "rest-after",
    "rest-before",
    "richness",
    "right",
    "rotation",
    "rotation-point",
    "row-gap",
    "ruby-align",
    "ruby-merge",
    "ruby-position",
    "running",
    "scroll-behavior",
    "scroll-snap-align",
    "scroll-snap-stop",
    "scroll-snap-type",
    "shape-image-threshold",
    "shape-inside",
    "shape-margin",
    "shape-outside",
    "size",
    "speak",
    "speak-as",
    "speak-header",
    "speak-numeral",
    "speak-punctuation",
    "speech-rate",
    "src",
    "stop-color",
    "stop-opacity",
    "stress",
    "string-set",
    "stroke",
    "stroke-dasharray",
    "stroke-dashoffset",
    "stroke-linecap",
    "stroke-linejoin",
    "stroke-miterlimit",
    "stroke-opacity",
    "stroke-width",
    "tab-size",
    "table-layout",
    "text-align",
    "text-align-all",
    "text-align-last",
    "text-combine-upright",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-skip",
    "text-decoration-style",
    "text-emphasis",
    "text-emphasis-color",
    "text-emphasis-position",
    "text-emphasis-style",
    "text-indent",
    "text-justify",
    "text-orientation",
    "text-overflow",
    "text-rendering",
    "text-shadow",
    "text-size-adjust",
    "text-space-collapse",
    "text-transform",
    "text-underline-position",
    "text-wrap",
    "top",
    "touch-action",
    "transform",
    "transform-box",
    "transform-origin",
    "transform-style",
    "transition",
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
    "unicode-bidi",
    "user-select",
    "vertical-align",
    "visibility",
    "voice-balance",
    "voice-duration",
    "voice-family",
    "voice-pitch",
    "voice-range",
    "voice-rate",
    "voice-stress",
    "voice-volume",
    "volume",
    "white-space",
    "widows",
    "width",
    "will-change",
    "word-break",
    "word-spacing",
    "word-wrap",
    "writing-mode",
    "z-index"
  ],
  "Exemplo": [
    "accent-color: red;",
    "align-content: center;",
    "align-items: flex-start;",
    "align-self: stretch;",
    "alignment-adjust: auto;",
    "alignment-baseline: baseline;",
    "all: initial;",
    "anchor-point: 0.5 0.5;",
    "animation: myAnimation 2s linear infinite;",
    "animation-delay: 1s;",
    "animation-direction: alternate;",
    "animation-duration: 3s;",
    "animation-fill-mode: forwards;",
    "animation-iteration-count: infinite;",
    "animation-name: slidein;",
    "animation-play-state: running;",
    "animation-timing-function: ease-in-out;",
    "appearance: none;",
    "aspect-ratio: 16/9;",
    "backdrop-filter: blur(5px);",
    "backface-visibility: hidden;",
    "background: linear-gradient(red, yellow);",
    "background-attachment: fixed;",
    "background-blend-mode: multiply;",
    "background-clip: padding-box;",
    "background-color: #f0f0f0;",
    "background-image: url('background.jpg');",
    "background-origin: content-box;",
    "background-position: center;",
    "background-repeat: no-repeat;",
    "background-size: cover;",
    "baseline-shift: super;",
    "block-size: 100px;",
    "border: 1px solid #000;",
    "border-block: 2px solid #ccc;",
    "border-block-color: #eee;",
    "border-block-end: 1px solid #888;",
    "border-block-end-color: #999;",
    "border-block-end-style: dashed;",
    "border-block-end-width: 2px;",
    "border-block-start: 1px solid #777;",
    "border-block-start-color: #666;",
    "border-block-start-style: dotted;",
    "border-block-start-width: 3px;",
    "border-block-style: solid;",
    "border-block-width: 2px;",
    "border-bottom: 1px solid #333;",
    "border-bottom-color: #444;",
    "border-bottom-left-radius: 5px;",
    "border-bottom-right-radius: 8px;",
    "border-bottom-style: solid;",
    "border-bottom-width: 3px;",
    "border-collapse: collapse;",
    "border-color: #555;",
    "border-end-end-radius: 7px;",
    "border-end-start-radius: 4px;",
    "border-image: url('border.png') 30 30 round;",
    "border-image-outset: 10px;",
    "border-image-repeat: round;",
    "border-image-slice: 20%;",
    "border-image-source: url('border.png');",
    "border-image-width: 5px;",
    "border-inline: 2px solid #bbb;",
    "border-inline-color: #aaa;",
    "border-inline-end: 3px solid #999;",
    "border-inline-end-color: #888;",
    "border-inline-end-style: double;",
    "border-inline-end-width: 4px;",
    "border-inline-start: 5px solid #777;",
    "border-inline-start-color: #666;",
    "border-inline-start-style: groove;",
    "border-inline-start-width: 6px;",
    "border-inline-style: inset;",
    "border-inline-width: 7px;",
    "border-left: 1px dashed #333;",
    "border-left-color: #444;",
    "border-left-style: solid;",
    "border-left-width: 2px;",
    "border-radius: 10px;",
    "border-right: 1px dotted #555;",
    "border-right-color: #666;",
    "border-right-style: solid;",
    "border-right-width: 3px;",
    "border-spacing: 5px;",
    "border-start-end-radius: 12px;",
    "border-start-start-radius: 15px;",
    "border-style: outset;",
    "border-top: 1px solid #777;",
    "border-top-color: #888;",
    "border-top-left-radius: 6px;",
    "border-top-right-radius: 9px;",
    "border-top-style: double;",
    "border-top-width: 4px;",
    "border-width: 2px;",
    "bottom: 20px;",
    "box-decoration-break: clone;",
    "box-shadow: 3px 3px 5px #ccc;",
    "box-sizing: border-box;",
    "break-after: always;",
    "break-before: always;",
    "break-inside: avoid;",
    "caption-side: bottom;",
    "caret-color: blue;",
    "clear: both;",
    "clip: rect(10px, 50px, 30px, 20px);",
    "clip-path: polygon(0% 0%, 100% 0%, 100% 100%, 0% 80%);",
    "color: #333;",
    "color-adjust: exact;",
    "column-count: 3;",
    "column-fill: auto;",
    "column-gap: 20px;",
    "column-rule: 1px solid #999;",
    "column-rule-color: #888;",
    "column-rule-style: dotted;",
    "column-rule-width: 2px;",
    "column-span: all;",
    "column-width: 100px;",
    "columns: 2 150px;",
    "contain: strict;",
    "content: attr(data-text);",
    "counter-increment: section 1;",
    "counter-reset: chapter 0;",
    "counter-set: page 1;",
    "cue: url('cue.mp3');",
    "cue-after: url('cue-after.mp3');",
    "cue-before: url('cue-before.mp3');",
    "cursor: pointer;",
    "direction: rtl;",
    "display: block;",
    "empty-cells: show;",
    "filter: blur(5px);",
    "flex: 1;",
    "flex-basis: auto;",
    "flex-direction: row-reverse;",
    "flex-flow: row nowrap;",
    "flex-grow: 2;",
    "flex-shrink: 1;",
    "flex-wrap: wrap;",
    "float: left;",
    "flood-color: #f0f;",
    "flood-opacity: 0.5;",
    "flow-from: flow;",
    "flow-into: flow;",
    "font: italic small-caps bold 16px/1.5 Arial, sans-serif;",
    "font-family: 'Times New Roman', Times, serif;",
    "font-feature-settings: 'liga' 1, 'clig' 0;",
    "font-kerning: normal;",
    "font-language-override: 'SRB';",
    "font-optical-sizing: auto;",
    "font-size: 18px;",
    "font-size-adjust: 0.5;",
    "font-stretch: condensed;",
    "font-style: oblique;",
    "font-synthesis: weight style;",
    "font-variant: small-caps;",
    "font-variant-caps: small-caps;",
    "font-variant-east-asian: ruby;",
    "font-variant-ligatures: no-common-ligatures;",
    "font-variant-numeric: ordinal;",
    "font-variant-position: sub;",
    "font-weight: bold;",
    "gap: 10px;",
    "glyph-orientation-vertical: 90deg;",
    "grid: auto / 1fr 2fr;",
    "grid-area: header;",
    "grid-auto-columns: 100px;",
    "grid-auto-flow: row dense;",
    "grid-auto-rows: minmax(100px, auto);",
    "grid-column: 1 / span 2;",
    "grid-column-end: 3;",
    "grid-column-gap: 10px;",
    "grid-column-start: 1;",
    "grid-gap: 10px 5px;",
    "grid-row: 2 / span 3;",
    "grid-row-end: 4;",
    "grid-row-gap: 15px;",
    "grid-row-start: 2;",
    "grid-template: 100px / 1fr 2fr;",
    "grid-template-areas: 'header header' 'nav main' 'footer footer';",
    "grid-template-columns: repeat(3, 100px);",
    "grid-template-rows: 100px auto;",
    "hanging-punctuation: first;",
    "height: 200px;",
    "hyphens: auto;",
    "image-orientation: from-image;",
    "image-rendering: auto;",
    "image-resolution: 300dpi;",
    "ime-mode: auto;",
    "initial-letters: 3 2;",
    "initial-letters-align: alphabetic;",
    "inline-size: 300px;",
    "inline-box-align: last baseline;",
    "justify-content: space-between;",
    "justify-items: center;",
    "justify-self: start;",
    "left: 50px;",
    "letter-spacing: 2px;",
    "lighting-color: #ccc;",
    "line-break: strict;",
    "line-clamp: 3;",
    "line-height: 1.5;",
    "line-height-step: 10px;",
    "list-style: square inside;",
    "list-style-image: url('list.png');",
    "list-style-position: outside;",
    "list-style-type: upper-roman;",
    "margin: 10px;",
    "margin-block: 15px;",
    "margin-block-end: 20px;",
    "margin-block-start: 25px;",
    "margin-bottom: 30px;",
    "margin-inline: 35px;",
    "margin-inline-end: 40px;",
    "margin-inline-start: 45px;",
    "margin-left: 50px;",
    "margin-right: 55px;",
    "margin-top: 60px;",
    "marker: none;",
    "marker-end: url('marker-end.svg');",
    "marker-knockout-left: discard;",
    "marker-knockout-right: discard;",
    "marker-mid: url('marker-mid.svg');",
    "marker-pattern: url('marker-pattern.svg');",
    "marker-segment: url('marker-segment.svg');",
    "marker-side: start;",
    "marker-start: url('marker-start.svg');",
    "mask: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,1));",
    "mask-box: fill-box;",
    "mask-box-outset: 5px;",
    "mask-box-repeat: round;",
    "mask-box-slice: 30% 20%;",
    "mask-box-source: url('mask-box.png');",
    "mask-box-width: auto;",
    "mask-clip: border-box;",
    "mask-composite: add;",
    "mask-image: url('mask.png');",
    "mask-mode: luminance;",
    "mask-origin: content-box;",
    "mask-position: center;",
    "mask-repeat: no-repeat;",
    "mask-size: cover;",
    "mask-source-type: url('mask-source.svg');",
    "mask-type: alpha;",
    "max-block-size: 300px;",
    "max-height: 500px;",
    "max-inline-size: 400px;",
    "max-width: 600px;",
    "min-block-size: 100px;",
    "min-height: 200px;",
    "min-inline-size: 150px;",
    "min-width: 250px;",
    "mix-blend-mode: overlay;",
    "move-to: main;",
    "nav-down: next;",
    "nav-left: sibling;",
    "nav-right: sibling;",
    "nav-up: previous;",
    "object-fit: cover;",
    "object-position: center;",
    "offset: 10px 20px;",
    "offset-anchor: auto;",
    "offset-distance: 30px;",
    "offset-path: path('offset-path.svg');",
    "offset-position: auto;",
    "offset-rotate: 45deg;",
    "opacity: 0.8;",
    "order: 2;",
    "orphans: 2;",
    "outline: 2px solid blue;",
    "outline-color: red;",
    "outline-offset: 3px;",
    "outline-style: dotted;",
    "outline-width: 4px;",
    "overflow: hidden;",
    "overflow-block: scroll;",
    "overflow-inline: auto;",
    "overflow-wrap: break-word;",
    "overflow-x: hidden;",
    "overflow-y: scroll;",
    "padding: 10px;",
    "padding-block: 15px;",
    "padding-block-end: 20px;",
    "padding-block-start: 25px;",
    "padding-bottom: 30px;",
    "padding-inline: 35px;",
    "padding-inline-end: 40px;",
    "padding-inline-start: 45px;",
    "padding-left: 50px;",
    "padding-right: 55px;",
    "padding-top: 60px;",
    "page: auto;",
    "page-break-after: always;",
    "page-break-before: left;",
    "page-break-inside: avoid;",
    "pause: 3s;",
    "pause-after: 2s;",
    "pause-before: 1s;",
    "perspective: 1000px;",
    "perspective-origin: 50% 50%;",
    "pitch: 100Hz;",
    "pitch-range: 50Hz;",
    "place-content: center space-between;",
    "place-items: center end;",
    "place-self: start center;",
    "play-during: auto;",
    "pointer-events: none;",
    "position: absolute;",
    "quotes: '«' '»' '‹' '›';",
    "region-break-after: avoid;",
    "region-break-before: avoid;",
    "region-break-inside: avoid;",
    "region-fragment: auto;",
    "resize: both;",
    "rest: 3s;",
    "rest-after: 2s;",
    "rest-before: 1s;",
    "richness: 50%;",
    "right: 100px;",
    "rotation: 45deg;",
    "rotation-point: 50% 50%;",
    "row-gap: 10px;",
    "ruby-align: start;",
    "ruby-merge: separate;",
    "ruby-position: over;",
    "running: none;",
    "scroll-behavior: smooth;",
    "scroll-snap-align: center;",
    "scroll-snap-stop: normal;",
    "scroll-snap-type: x mandatory;",
    "shape-image-threshold: 0.5;",
    "shape-inside: inset(10%);",
    "shape-margin: 20px;",
    "shape-outside: url('shape.svg');",
    "size: A4;",
    "speak: normal;",
    "speak-as: spell-out;",
    "speak-header: once;",
    "speak-numeral: digits;",
    "speak-punctuation: code;",
    "speech-rate: medium;",
    "src: url('font.woff2');",
    "stop-color: #f00;",
    "stop-opacity: 0.8;",
    "stress: 50%;",
    "string-set: title content(h2);",
    "stroke: #00f;",
    "stroke-dasharray: 5 10;",
    "stroke-dashoffset: 2px;",
    "stroke-linecap: round;",
    "stroke-linejoin: bevel;",
    "stroke-miterlimit: 4;",
    "stroke-opacity: 0.6;",
    "stroke-width: 3px;",
    "tab-size: 4;",
    "table-layout: fixed;",
    "text-align: center;",
    "text-align-all: center;",
    "text-align-last: right;",
    "text-combine-upright: all;",
    "text-decoration: underline;",
    "text-decoration-color: #00f;",
    "text-decoration-line: overline;",
    "text-decoration-skip: ink;",
    "text-decoration-style: wavy;",
    "text-emphasis: circle;",
    "text-emphasis-color: red;",
    "text-emphasis-position: over right;",
    "text-emphasis-style: filled;",
    "text-indent: 20px;",
    "text-justify: inter-word;",
    "text-orientation: mixed;",
    "text-overflow: ellipsis;",
    "text-rendering: optimizeSpeed;",
    "text-shadow: 2px 2px 2px #000;",
    "text-size-adjust: auto;",
    "text-space-collapse: discard;",
    "text-transform: uppercase;",
    "text-underline-position: under;",
    "text-wrap: balance;",
    "top: 80px;",
    "touch-action: manipulation;",
    "transform: rotate(45deg);",
    "transform-box: fill-box;",
    "transform-origin: top left;",
    "transform-style: preserve-3d;",
    "transition: all 0.3s ease-in-out;",
    "transition-delay: 0.2s;",
    "transition-duration: 0.5s;",
    "transition-property: opacity;",
    "transition-timing-function: ease-out;",
    "unicode-bidi: embed;",
    "user-select: none;",
    "vertical-align: middle;",
    "visibility: hidden;",
    "voice-balance: left;",
    "voice-duration: 3s;",
    "voice-family: 'Alex', sans-serif;",
    "voice-pitch: low;",
    "voice-range: 90Hz;",
    "voice-rate: medium;",
    "voice-stress: moderate;",
    "voice-volume: 75%;",
    "volume: 0.5;",
    "white-space: nowrap;",
    "widows: 2;",
    "width: 300px;",
    "will-change: transform;",
    "word-break: break-all;",
    "word-spacing: 5px;",
    "word-wrap: break-word;",
    "writing-mode: vertical-lr;",
    "z-index: 1000;"
  ]
}


linhas_commands = len(data_completa["comando"])
linhas_exemplo = len(data_completa["Exemplo"])

# Se os tamanhos forem iguais, crie o DataFrame
if linhas_exemplo != linhas_commands:
  print("Linhas de comandos --> ", linhas_commands)
  print("Linhas de exemplos --> ", linhas_exemplo)
else:
  df = pd.DataFrame(data_completa)
  file_path = "comandos_CSS.xlsx"
  df.to_excel(file_path, index=False)
  print(file_path)


